server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:conversations;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop

sprout:
  enabled: true
  scan:
    base-packages: io.github.ivannavas.sprout.example.spring
